from __future__ import annotations

from __future__ import absolute_import
from typing import Optional, TypedDict

_LOR_SUFFIX = "(LOR)"
_LOR_BOOST = 1.08


# ── Payload Definition ────────────────────────────────────────────────────────
class BallOutcome(TypedDict):
    """
    Standardized payload generated by logic.py and consumed by views.py/game.py.
    """

    outcome_str: str
    runs_batter: int
    runs_extras: int
    is_legal: bool
    extra_type: str | None
    dismissal_type: str | None
    timing_label: str
    overthrows: int
    umpire_given_out: bool
    actual_is_out: bool
    drs_eligible_wicket: bool
    review_reason: str | None
    free_hit_saved: bool
    is_actual_nb: bool
    umpire_called_nb: bool
    drs_eligible_nb: bool
    nb_review_reason: str | None


# ── Global Mappings ───────────────────────────────────────────────────────────
ROLE_EMOJIS = {"Bat": "🏏", "Bowl": "⚾", "AR": "⚔️", "WK": "🧤"}
# ── LOR Bonus ─────────────────────────────────────────────────────────────────


def has_lor_bonus(ball) -> bool:
    """Return True if the cricketer's name ends with the '(LOR)' suffix."""
    try:
        name = getattr(ball, "country", "") or ""
        return name.strip().endswith(_LOR_SUFFIX)
    except Exception:
        return False


def apply_lor_bonus(bat: int, bowl: int) -> tuple[int, int]:
    """Apply the +8% LOR bonus to both batting and bowling stats."""
    if bat or bowl:
        bat = int(round(bat * _LOR_BOOST))
        bowl = int(round(bowl * _LOR_BOOST))
    return bat, bowl


# ── Shiny Bonus ──────────────────────────────────────────────────────────────
# A Shiny special card is 1.25x stronger than its plain (special = none) twin.
_SHINY_BOOST = 1.25


def is_shiny(inst) -> bool:
    """Return True if the cricketer instance carries the Shiny special."""
    try:
        special = getattr(inst, "special", None)
        if special is None:
            return False
        name = getattr(special, "name", "") or ""
        return name.strip().lower() == "shiny"
    except Exception:
        return False


def apply_shiny_boost(ovr: int, bat: int, bowl: int) -> tuple[int, int, int]:
    """Apply the +25% Shiny bonus to OVR, batting and bowling stats."""
    if ovr or bat or bowl:
        ovr = int(round(ovr * _SHINY_BOOST))
        bat = int(round(bat * _SHINY_BOOST))
        bowl = int(round(bowl * _SHINY_BOOST))
    return ovr, bat, bowl


# ── Premium / Signature Event Bonus ─────────────────────────────────────────
# Cards belonging to PREMIUM EDITION EVENT or SIGNATURE EDITION EVENT get
# a +25% boost to OVR, batting and bowling stats.
_PREMIUM_SIG_BOOST = 1.25


def is_premium_or_signature_event(inst) -> bool:
    """Return True if the instance belongs to a Premium or Signature Edition Event special."""
    try:
        special = getattr(inst, "special", None)
        if special is None:
            return False
        name = getattr(special, "name", "") or ""
        is_event = getattr(special, "is_event", False)
        upper = name.strip().upper()
        return is_event and ("PREMIUM" in upper or "SIGNATURE" in upper)
    except Exception:
        return False


def apply_premium_signature_boost(
    ovr: int, bat: int, bowl: int
) -> tuple[int, int, int]:
    """Apply the +25% Premium/Signature Edition Event bonus to OVR, batting and bowling stats."""
    if ovr or bat or bowl:
        ovr = int(round(ovr * _PREMIUM_SIG_BOOST))
        bat = int(round(bat * _PREMIUM_SIG_BOOST))
        bowl = int(round(bowl * _PREMIUM_SIG_BOOST))
    return ovr, bat, bowl


# ── Memories Event Bonus ─────────────────────────────────────────────────────
# Cards belonging to the MEMORIES event get a +20% boost to OVR, batting and bowling stats.
_MEMORIES_BOOST = 1.20


def is_memories_event(inst) -> bool:
    """Return True if the instance belongs to the MEMORIES event special."""
    try:
        special = getattr(inst, "special", None)
        if special is None:
            return False
        name = getattr(special, "name", "") or ""
        is_event = getattr(special, "is_event", False)
        return is_event and name.strip().upper() == "MEMORIES"
    except Exception:
        return False


def apply_memories_boost(ovr: int, bat: int, bowl: int) -> tuple[int, int, int]:
    """Apply the +20% Memories event bonus to OVR, batting and bowling stats."""
    if ovr or bat or bowl:
        ovr = int(round(ovr * _MEMORIES_BOOST))
        bat = int(round(bat * _MEMORIES_BOOST))
        bowl = int(round(bowl * _MEMORIES_BOOST))
    return ovr, bat, bowl


# ── Player of the Month (POTM) Bonus ─────────────────────────────────────────
# Cards belonging to the POTM event get a +25% boost to their higher stat
# (batting or bowling), +20% to OVR, and +10% to the lower stat.
_POTM_BOOST = 1.25
_POTM_OVR_BOOST = 1.20
_POTM_LOWER_BOOST = 1.10


def is_potm_event(inst) -> bool:
    """Return True if the instance belongs to the Player of the Month (POTM) event special."""
    try:
        special = getattr(inst, "special", None)
        if special is None:
            return False
        name = getattr(special, "name", "") or ""
        is_event = getattr(special, "is_event", False)
        upper = name.strip().upper()
        return is_event and ("POTM" in upper or "PLAYER OF THE MONTH" in upper)
    except Exception:
        return False


def apply_potm_boost(ovr: int, bat: int, bowl: int) -> tuple[int, int, int]:
    """Apply the POTM bonus: 1.25x to the higher stat, 1.10x to the lower stat, 1.20x to OVR."""
    if not (ovr or bat or bowl):
        return ovr, bat, bowl
    if bat >= bowl:
        bat = int(round(bat * _POTM_BOOST))
        bowl = int(round(bowl * _POTM_LOWER_BOOST))
    else:
        bowl = int(round(bowl * _POTM_BOOST))
        bat = int(round(bat * _POTM_LOWER_BOOST))
    ovr = int(round(ovr * _POTM_OVR_BOOST))
    return ovr, bat, bowl


# ── Special Memories Player Detection ───────────────────────────────────────
_MEMORIES_SPECIAL_PLAYERS = {
    "chris gayle": "gayle",
    "brendon mccullum": "mccullum",
}


def get_memories_player_type(inst) -> str | None:
    """Return the special player type if this is a MEMORIES special card, else None."""
    try:
        special = getattr(inst, "special", None)
        if special is None:
            ball = getattr(inst, "ball", None)
            if ball is not None:
                special = getattr(ball, "special", None)
        if special is None:
            return None
        if not getattr(special, "is_event", False):
            return None
        if getattr(special, "name", "").strip().upper() != "MEMORIES":
            return None
        name = getattr(inst, "country", None) or ""
        if not name and hasattr(inst, "ball"):
            name = getattr(inst.ball, "country", "") or ""
        name = name.lower().strip()
        for key, val in _MEMORIES_SPECIAL_PLAYERS.items():
            if key in name:
                return val
    except Exception:
        pass
    return None


# ── Database Instance Helpers ─────────────────────────────────────────────────
def get_cricket_stats(ball) -> tuple[int, int, int]:
    """Fetch OVR, BAT, and BOWL stats from capacity_logic."""
    try:
        logic = getattr(ball, "capacity_logic", None) or {}
        ovr = logic.get("ovr", 0)
        bat = logic.get("bat_power", 0)
        bowl = logic.get("bowl_power", 0)
        return int(ovr), int(bat), int(bowl)
    except Exception:
        return 0, 0, 0


def get_card_role(ball) -> str:
    """Determine primary playing role of the card from capacity_logic."""
    try:
        logic = getattr(ball, "capacity_logic", None) or {}
        role = logic.get("role")
        if role:
            return role
    except Exception:
        pass
    return "Bat"


def compute_ovr_from_rarity(rarity: float) -> int:
    if not rarity:
        return 99
    r = min(max(float(rarity), 0.0), 1.0)
    return max(1, min(99, int(round(99 - 98 * r))))


def is_match_eligible(ball) -> bool:
    """Validate if a card is eligible to be used in live T20 matches."""
    try:
        cap = getattr(ball, "capacity_name", "").lower()
        return cap not in ["team", "duo", "trio", "custom"]
    except Exception:
        return True


# ── Exchange Value ─────────────────────────────────────────────────────────
# Currency value assigned to a card for /sell and /exchange.
# Based on rarity (the badge rarity shown on the card) and special type.


def _rarity_to_base_value(rarity: float) -> int:
    """Convert rarity to base exchange value (before event multipliers)."""
    if not rarity or rarity <= 0:
        return 1

    r = float(rarity)

    exact = {
        0.01: 2000,
        0.02: 1200,
        0.03: 1000,
        0.05: 500,
        0.08: 200,
        0.1: 50,
        0.2: 20,
        0.3: 12,
        0.4: 8,
        0.5: 7,
        0.6: 6,
    }
    if r in exact:
        return exact[r]

    if 0.7 <= r <= 1.0:
        return 5
    if 1.0 < r < 5.0:
        return 3
    if 5.0 <= r < 10.0:
        return 2
    if 10.0 <= r < 20.0:
        return 1
    if r >= 20.0:
        return 1

    return 1


def compute_exchange_value(
    ball,
    special_name: str | None = None,
    is_event: bool = False,
    is_prime_event: bool = False,
) -> int:
    """Compute the currency exchange value for a card.

    Tier 1 (base value from rarity):
        - Non-event cards (no special)
        - ICONS event
        - Prime Event cards (Ball.prime_event=True)

    Tier 2 (2x base):
        - Signature Edition Event
        - Premium Edition Event

    Tier 3 (1.25x base):
        - All other events

    Shiny specials (5x base):
        - Any card with a Shiny special overlay
    """
    logic = getattr(ball, "capacity_logic", None) or {}
    badge_r = logic.get("badge_rarity")
    if badge_r is not None:
        try:
            rarity = float(badge_r)
        except (TypeError, ValueError):
            rarity = float(getattr(ball, "rarity", 1.0) or 1.0)
    else:
        rarity = float(getattr(ball, "rarity", 1.0) or 1.0)

    base = _rarity_to_base_value(rarity)

    if is_prime_event:
        return base
    if is_event and special_name and special_name.strip().upper() == "ICONS":
        return base

    if special_name and special_name.strip().lower() == "shiny":
        return base * 5

    if special_name and special_name.strip().lower() == "transformers":
        return base * 2

    if is_event and special_name:
        upper = special_name.strip().upper()
        if "PREMIUM" in upper or "SIGNATURE" in upper:
            return base * 2

    if is_event:
        return int(round(base * 1.25))

    return base


# ── Narrative Attribute System ───────────────────────────────────────────────
# Predefined narrative attributes matching real cricket history.
# Each attribute has:
#   - "description": real-world context
#   - "bat_effects": batting modifiers
#   - "bowl_effects": bowling modifiers
#   - "field_effects": fielding modifiers
#   - "apply": custom callback for complex logic

NARRATIVE_ATTRIBUTES = {
    "lethal_pace": {
        "description": "Extreme speed bowler (Shoaib Akhtar, Brett Lee, Jeff Thomson). Bouncers and yorkers become unplayable.",
        "bat_effects": {},
        "bowl_effects": {
            "bouncer_wicket_mult": 1.4,
            "yorker_wicket_mult": 1.3,
            "pace_bonus": 1.15,
        },
        "field_effects": {},
        "apply": None,
    },
    "six_hitter": {
        "description": "Boundary clearing power (Chris Gayle, MS Dhoni, Herschelle Gibbs). Higher six probability with elevated risk.",
        "bat_effects": {"six_mult": 1.25, "four_mult": 0.90, "wicket_risk": 1.15},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "finisher": {
        "description": "Death-over finisher (MS Dhoni, Ben Stokes, Jos Buttler). Accelerates under pressure in final overs.",
        "bat_effects": {"death_over_bonus": 1.20, "chase_bonus": 1.10},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "cover_drive_specialist": {
        "description": "Sublime cover drive (Virat Kohli, Kumar Sangakkara). Dominates pace bowling on the front foot.",
        "bat_effects": {"front_foot_boundary_mult": 1.20, "pace_batting_bonus": 1.08},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "defensive_maestro": {
        "description": "Unbreakable defense (Rahul Dravid, Alastair Cook, Hashim Amla). Low wicket risk, patient against spin.",
        "bat_effects": {
            "wicket_defense_mult": 0.70,
            "spin_defense_bonus": 1.15,
            "dot_ball_tolerance": 1.10,
        },
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "solid_keeper_batter": {
        "description": "Wicket-keeper batter (Adam Gilchrist, MS Dhoni, Quinton de Kock). Strong behind stumps and with bat.",
        "bat_effects": {"wk_batting_bonus": 1.10},
        "bowl_effects": {},
        "field_effects": {"catch_mult": 1.15, "stumping_chance": 1.20},
        "apply": None,
    },
    "spin_master": {
        "description": "Spin wizard (Shane Warne, Muttiah Muralitharan, Daniel Vettori). Variations and turn cause chaos.",
        "bat_effects": {},
        "bowl_effects": {"spin_wicket_mult": 1.25, "variation_bonus": 1.10},
        "field_effects": {},
        "apply": None,
    },
    "death_bowler": {
        "description": "Death-over specialist (Jasprit Bumrah, Lasith Malinga, Trent Boult). Yorkers and slower balls at the death.",
        "bat_effects": {},
        "bowl_effects": {"yorker_death_mult": 1.35, "death_over_economy": 0.85},
        "field_effects": {},
        "apply": None,
    },
    "powerplay_specialist": {
        "description": "Powerplay dominator (Virender Sehwag, David Warner, Chris Gayle). Takes the attack to new-ball bowlers.",
        "bat_effects": {"powerplay_boundary_mult": 1.25, "early_over_risk": 1.10},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "reliable_death": {
        "description": "Reliable finisher under pressure (MS Dhoni, Eoin Morgan, Michael Hussey). Cool under pressure.",
        "bat_effects": {
            "death_over_bonus": 1.15,
            "pressure_six_mult": 1.10,
            "wicket_pressure_mult": 0.85,
        },
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "reverse_sweep_master": {
        "description": "Unorthodox genius (AB de Villiers, Glenn Maxwell, Rashid Khan). Reverse sweeps and 360-degree hitting.",
        "bat_effects": {"reverse_sweep_mult": 1.40, "unorthodox_boundary_mult": 1.15},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "leg_spin_specialist": {
        "description": "Leg spin magician (Shane Warne, Anil Kumble, Rashid Khan). Wrong 'un and googly cause regular wickets.",
        "bat_effects": {},
        "bowl_effects": {"leg_spin_wicket_mult": 1.30, "googly_effectiveness": 1.20},
        "field_effects": {},
        "apply": None,
    },
    "opening_bulwark": {
        "description": "Solid opening batsman (Jack Hobbs, Sunil Gavaskar, Geoffrey Boycott). Wears down new-ball bowlers.",
        "bat_effects": {
            "new_ball_defense": 1.20,
            "early_over_wicket_risk": 0.80,
            "leave_ability": 1.15,
        },
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "clutch_fielder": {
        "description": "Elite fielder (Jonty Rhodes, Herschelle Gibbs, Ravindra Jadeja). Converts half-chances into run-outs/catches.",
        "bat_effects": {},
        "bowl_effects": {},
        "field_effects": {
            "catch_mult": 1.30,
            "run_out_chance": 1.40,
            "direct_hit_chance": 1.25,
        },
        "apply": None,
    },
    "death_over_explosive": {
        "description": "Explosive finisher (Andre Russell, Hardik Pandya, Dwayne Smith). Massive hitting in final overs.",
        "bat_effects": {
            "death_over_bonus": 1.30,
            "six_mult": 1.15,
            "wicket_risk": 1.20,
        },
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "swing_king": {
        "description": "Swing bowling master (Wasim Akram, James Anderson, Glenn McGrath). Moves the ball both ways in air.",
        "bat_effects": {},
        "bowl_effects": {"swing_wicket_mult": 1.25, "new_ball_danger": 1.20},
        "field_effects": {},
        "apply": None,
    },
    "the_wall": {
        "description": "Unbreakable batting wall (Rahul Dravid). Wicket risk drops significantly, perfect for long innings.",
        "bat_effects": {"wicket_risk": 0.75, "four_mult": 0.95},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "master_blaster": {
        "description": "The Master Blaster (Sachin Tendulkar). Consistent boundary threat with controlled aggression.",
        "bat_effects": {"four_mult": 1.15, "six_mult": 1.05, "wicket_risk": 0.90},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "king_kohli": {
        "description": "The King (Virat Kohli). Chases targets with ruthless efficiency, thrives under pressure.",
        "bat_effects": {
            "death_over_bonus": 1.15,
            "four_mult": 1.10,
            "wicket_risk": 0.95,
        },
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "goat": {
        "description": "Greatest of All Time (Sachin Tendulkar / Virat Kohli). All-round batting excellence with elite consistency.",
        "bat_effects": {"four_mult": 1.10, "six_mult": 1.05, "wicket_risk": 0.85},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "world_cup_hero": {
        "description": "Big stage performer (MS Dhoni, Yuvraj Singh). Rises to the occasion in tournament matches.",
        "bat_effects": {
            "death_over_bonus": 1.10,
            "six_mult": 1.10,
            "wicket_risk": 0.90,
        },
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "vivstruction": {
        "description": "The Viv Richards mentality — dominant, unshakable, and merciless. Higher batting output with reduced dismissal chance.",
        "bat_effects": {"four_mult": 1.10, "six_mult": 1.08, "wicket_risk": 0.80},
        "bowl_effects": {},
        "field_effects": {},
        "apply": None,
    },
    "bouncer_tyrant": {
        "description": "Relentless fast bowler (Dennis Lillee, Mitchell Johnson). Short-pitched bowling causes chaos.",
        "bat_effects": {},
        "bowl_effects": {"bouncer_wicket_mult": 1.35},
        "field_effects": {},
        "apply": None,
    },
    "yorker_king": {
        "description": "Death-over yorker specialist (Jasprit Bumrah, Lasith Malinga). Wrecking balls at the death.",
        "bat_effects": {},
        "bowl_effects": {"yorker_death_mult": 1.40, "yorker_wicket_mult": 1.20},
        "field_effects": {},
        "apply": None,
    },
}


def get_narrative_attributes(ball) -> list[str]:
    """Return list of active narrative attribute keys from ball.capacity_logic['narrative']."""
    try:
        logic = getattr(ball, "capacity_logic", None) or {}
        narrative = logic.get("narrative")
        if not narrative:
            return []
        if isinstance(narrative, dict):
            attrs = narrative.get("attributes", [])
            if isinstance(attrs, list):
                return [a for a in attrs if a in NARRATIVE_ATTRIBUTES]
        return []
    except Exception:
        return []


def get_narrative_effect(ball, attribute: str) -> dict:
    """Return the effect dict for a specific narrative attribute."""
    return NARRATIVE_ATTRIBUTES.get(attribute, {})
